/**
 * FamilyTreeAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GenderEnum } from './genderEnum';

export interface FamilyMember { 
    id?: string;
    firstname?: string;
    surname?: string;
    middlename?: string;
    readonly fullname?: string;
    gender?: GenderEnum;
    dateOfBirth?: Date;
    dateOfDeath?: Date;
    childs?: Array<FamilyMember>;
    parents?: Array<FamilyMember>;
}