/**
 * FamilyTreeAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type GenderEnum = 0 | 1 | 2;

export const GenderEnum = {
    NUMBER_0: 0 as GenderEnum,
    NUMBER_1: 1 as GenderEnum,
    NUMBER_2: 2 as GenderEnum
};